// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TOIStest.Data;

#nullable disable

namespace TOIStest.Migrations
{
    [DbContext(typeof(TOIStestContext))]
    [Migration("20220316160338_InitForTOIS")]
    partial class InitForTOIS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TOIStest.Models.Vorm_1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EAP")
                        .HasColumnType("int");

                    b.Property<string>("baseForCurriculum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("citationForField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("competenceOfTeacher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contentEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contentEstonian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contentRussian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("e_Study")
                        .HasColumnType("bit");

                    b.Property<string>("fieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fieldOfStudyDetailed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fieldOfTraining")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gradingCriteriaEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gradingCriteriaEstonian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gradingCriteriaRussian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gradingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("groupOfField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("independentStudy")
                        .HasColumnType("bit");

                    b.Property<string>("instituteOfMainSupervisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isOrganiser")
                        .HasColumnType("bit");

                    b.Property<bool?>("isSubscribable")
                        .HasColumnType("bit");

                    b.Property<bool>("isVisible")
                        .HasColumnType("bit");

                    b.Property<string>("mainSupervisorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameEstonian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameOfsupervisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameRussian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("practice")
                        .HasColumnType("bit");

                    b.Property<string>("reqEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reqEstonian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reqRussian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("someElse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyEnvironment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyForm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyGoalEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyGoalEstonian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyGoalRussian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyLanguages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyMethodsEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyMethodsEstonian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studyMethodsRussian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supervisorInstitute")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("targetGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacherNameOnWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("webName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vorm_1");
                });
#pragma warning restore 612, 618
        }
    }
}
